### ISSUE TITLE
Consider preferring eza over exa

### ISSUE THREAD

**Issue by 1wilkens** [zimfw/exa#1]
### Is your feature request related to a problem? Please describe.

As `exa` is [essentially unmaintained](https://github.com/ogham/exa/commit/fb05c421ae98e076989eb6e8b1bcf42c07c1d0fe), consider preferring the maintained community fork [`eza`](https://github.com/eza-community/eza) over it.

### Describe the solution you'd like

For compatibility reasons, the module should probably keep its name but check for eza's existence and prefer it over exa.
An edit in the README could point of the unmaintained nature of `exa` and encourage people to migrate.

### Describe alternatives you've considered

The `eza` aliases could also be implemented in a new eza module.

**Comment by ericbn** [comment]
Hi @1wilkens. I’m considering creating a separate zimfw/eza module for it.
