### ISSUE TITLE
Add --icons option

### ISSUE THREAD

**Issue by ArturNTx** [zimfw/exa#4]
### Is your feature request related to a problem? Please describe.

I added the plugin and realized that it is not possible to enable the exa/eza --icons option

### Describe the solution you'd like

add an option like zmodule exa --icons

### Describe alternatives you've considered

Manually add --icons parameter to init.zsh

**Comment by dylanleung** [comment]
Me too

**Comment by ericbn** [comment]
At the bottom of your `.zshrc` file you can override the `ls` alias with all the personalized parameters. E.g:
```zsh
alias ls='eza --group-directories-first --icons'
```
By default, the alias is just:
```zsh
alias ls='eza --group-directories-first'
```
